# Site settings
title: La Poterie du Vexin: Atelier de poterie dans l'Eure (27)

email: lapoterieduvexin@hotmail.fr
url: poterie-vexin.fr
description: "La Poterie du Vexin est un atelier de poterie situé à Muids dans l'Eure, entre la ville de Louviers et les Andelys. Des cours de poterie au tour y sont donnés et les céramiques de Pascale Garrigues y sont mises en vente."

# Color settings (hex-codes without the leading hash-tag)
color:
#  primary-dark: '#000000'
#  links: '#219ab3'

  primary-dark: '#FFFFFF'
  links: '#555555'

# Footer settings
footer: La Poterie du Vexin

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://fr-fr.facebook.com/lapoterieduvexin

# Build settings
markdown: kramdown
permalink: pretty
