# Site settings
title: "La Poterie du Vexin: Atelier de poterie dans l'Eure (27), Normandie, proche de Rouen, les Andelys et Louvier."

email: lapoterieduvexin@hotmail.fr
phone: "06 01 71 90 31"
url: https://poterie-vexin.fr
description: "La Poterie du Vexin est un atelier de poterie situé proche de Rouen à Amfreville sous les monts dans l'Eure, entre la ville de Louviers et les Andelys en Normandie. Des cours de poterie au tour y sont donnés et les céramiques de Pascale Garrigues y sont mises en vente."

# Color settings (hex-codes without the leading hash-tag)
color:
#  primary-dark: '#000000'
#  links: '#219ab3'

  text: '#291300'
  text-dark: '#ffe2d3e3'
  primary: '#643C2B'
  primary-dark: '#EAC9C1'
  secondary: '#D94E34'
  terciary: '#80704D'
  primary-dark: '#FFFFFF'
  links: '#D94E34'

# Footer settings
footer: La Poterie du Vexin

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://fr-fr.facebook.com/lapoterieduvexin

# Build settings
markdown: kramdown
permalink: pretty
